server:
  port: ${SPRING_PORT}

grpc:
  server:
    port: ${GRPC_PORT}

spring:
  application:
    name: keumbang-auth

  profiles:
    active: local

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

  devtools:
    restart:
      enabled: true

# JWT 설정
jwt:
  secret: ${JWT_SECRET}

logging:
  config: classpath:logback-${spring.profiles.active}.xml

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: prod
